# Generated by Django 4.2.26 on 2025-11-14 21:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the job', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Human-readable name for the job', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', help_text='Current status of the job', max_length=20)),
                ('config', models.JSONField(default=dict, help_text='Configuration parameters for the extraction job')),
                ('record_count', models.IntegerField(default=0, help_text='Number of records extracted')),
                ('error_message', models.TextField(blank=True, help_text='Error message if job failed', null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When the job was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the job was last updated')),
                ('start_time', models.DateTimeField(blank=True, help_text='When the job started processing', null=True)),
                ('end_time', models.DateTimeField(blank=True, help_text='When the job finished (completed, failed, or cancelled)', null=True)),
            ],
            options={
                'verbose_name': 'Extraction Job',
                'verbose_name_plural': 'Extraction Jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='api_job_status_a9a0fa_idx'), models.Index(fields=['created_at'], name='api_job_created_f81cf5_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExtractionResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the result', primary_key=True, serialize=False)),
                ('data', models.JSONField(help_text='The extracted data record (JSON format)')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When the result was created')),
                ('job', models.ForeignKey(help_text='The extraction job this result belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api.job')),
            ],
            options={
                'verbose_name': 'Extraction Result',
                'verbose_name_plural': 'Extraction Results',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['job', 'created_at'], name='api_extract_job_id_dab4db_idx')],
            },
        ),
    ]
